<form method="post">
	<div class="form-row">
		<div class="form-group col-md-6">
			<label for="inputEmail4" class="col-form-label">First Name</label>
			<input type="text" class="form-control" id="inputEmail4" placeholder="" name="idFirstName">
		</div>
		<div class="form-group col-md-6">
			<label for="inputPassword4" class="col-form-label">Last Name</label>
			<input type="text" class="form-control" id="inputPassword4" placeholder="" name="idLastName">
		</div>
	</div>
	<div class="form-group">
	<label for="inputAddress" class="col-form-label">Users</label>
		<input type="text" class="form-control" id="inputAddress" placeholder="" name="idUsers">
	</div>
	<div class="form-group">
		<label for="inputAddress2" class="col-form-label">Password</label>
		<input type="password" class="form-control" id="inputAddress2" placeholder="" name="idPass">
	</div> 
	<button type="submit" class="btn btn-primary" name="btRegister">Register</button>
</form>