
<p><?php $this->flashSession->output() ?></p>
<form method="POST">
<h1>Login</h1>

  
   <div class="form-row">
   <label>User</label>
      <input type="text" class="form-control" placeholder="User" name="edUser">
    </div>
    <div class="form-row">
    <label>Password</label>
      <input type="text" class="form-control" placeholder="Password" name="edPassword">
    </div> <br><br>
 <button type="submit" class="btn btn-primary">Login</button>

   <a href="register" class="btn btn-primary">Register</a>
  </div>

</form>


<!-- <form action="" method="post" accept-charset="utf-8">
<h1>LOGIN</h1>
    <input type="text" name="edUser" placeholder="User name" >
    <input type="password" name="edPassword" placeholder="Password">
    <button type="">Login</button>
</form>
 -->






