
<p><?php $this->flashSession->output() ?></p>
<form method="post">
    <h1>Login</h1>>
  <div class="form-group">
		<label for="inputAddress" class="col-form-label">Users</label>
		<input type="text" class="form-control" id="inputAddress" placeholder="" name="edUsers">
	</div>
	<div class="form-group">
		<label for="inputAddress2" class="col-form-label">Password</label>
		<input type="password" class="form-control" id="inputAddress2" placeholder="" name="edPassword">
	</div> 
	<button type="submit" class="btn btn-primary" name="btRegister">Login</button>
	<a class="btn btn-primary" href="register">Register</a>

</form>


<!-- <form action="" method="post" accept-charset="utf-8">
<h1>LOGIN</h1>
    <input type="text" name="edUser" placeholder="User name" >
    <input type="password" name="edPassword" placeholder="Password">
    <button type="">Login</button>
</form>
 -->






