<form method="post">
	<div class="form-group">
		<label for="inputAddress" class="col-form-label">Users</label>
		<input type="text" class="form-control" id="inputAddress" placeholder="" name="idUsers">
	</div>
	<div class="form-group">
		<label for="inputAddress2" class="col-form-label">Password</label>
		<input type="password" class="form-control" id="inputAddress2" placeholder="" name="idPass">
	</div> 
	<button type="submit" class="btn btn-primary" name="btRegister">Login</button>
	<a class="btn btn-primary" href="/Phalcon/jobcv/register">Register</a>
</form>