<form method="POST">
<h1>Register</h1>
  <div class="form-row">
    <div class="col">
    <label>First name</label>
      <input type="text" class="form-control" placeholder="First name" name="edFirstName">
    </div>
    <div class="col">
      <label>Last name</label>
      <input type="text" class="form-control" placeholder="Last name" name="edLastName">
    </div>

  </div>
  
   <div class="form-row">
   <label>User</label>
      <input type="text" class="form-control" placeholder="User" name="edUser">
    </div>
    <div class="form-row">
    <label>Password</label>
      <input type="text" class="form-control" placeholder="Password" name="edPassword">
    </div> <br><br>
 <button type="submit" class="btn btn-primary">Đăng ký</button>

  </div>

</form>